name: Build Socket Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Compilar
        run: python setup.py build_ext --inplace
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: socket-compilado
          path: _socket*.pyd
